apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-service
spec:
  selector:
    app: api-service
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  selector:
    matchLabels:
      app: api-service
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      name: api-service
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: {{ image reference }}
        envFrom:
        - configMapRef:
            name: sampleapp-configmap
        - secretRef:
            name: sampleapp-secret
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 25m
