apiVersion: v1
kind: Secret
metadata:
  name: sampleapp-secret
type: Opaque
data:
  MONGO_USERNAME: YWRtaW4=
  MONGO_PASSWORD: V1RtSk5FeHJGeFB1JTRVSg==
  KEYCLOAK_USERNAME: YWRtaW4=
  KEYCLOAK_PASSWORD: V3ByUmJzciEydGoyIzVReQ==
  MYSQL_USER: YWRtaW4=
  MYSQL_PASSWORD: OTJBUmo2OCYmNmV0ZGI4Uw==
  MYSQL_ROOT_PASSWORD: bXlwYXNzd29yZA==